-- daily_rank_snapshot: yesterday's weekly ranking, kept for the rank-up mission (BEA-299).
--
-- Flyway is not used in this repository, so this DDL is applied by hand.
-- Production runs ddl-auto=validate: apply this BEFORE deploying the entity,
-- otherwise the application fails to boot.
--
-- Requires app_user and ranking_season to exist.
--
-- The snapshot is taken at 23:55, not right after midnight: a snapshot taken
-- the moment the weekly season resets would record everyone at zero, and the
-- next day's mission would compare against that meaningless order.
--
-- season_id is stored so the mission can refuse to judge across a reset. On
-- Monday yesterday's snapshot belongs to the previous season, and comparing
-- the two would hand every user the rank-up reward for free.

BEGIN;

CREATE TABLE daily_rank_snapshot (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       UUID NOT NULL REFERENCES app_user (id),
    snapshot_date DATE NOT NULL,
    season_id     BIGINT NOT NULL REFERENCES ranking_season (id),
    rank_value    INTEGER NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL,
    CONSTRAINT ck_daily_rank_snapshot_rank CHECK (rank_value > 0)
);

CREATE UNIQUE INDEX uq_daily_rank_snapshot_user_date ON daily_rank_snapshot (user_id, snapshot_date);

-- 오래된 스냅샷을 정리할 때 쓴다. 미션 판정은 어제 것만 보므로 며칠치만 있으면 된다.
CREATE INDEX ix_daily_rank_snapshot_date ON daily_rank_snapshot (snapshot_date);

COMMIT;

-- Verification after applying:
--   SELECT conname FROM pg_constraint WHERE conrelid = 'daily_rank_snapshot'::regclass ORDER BY conname;
--   SELECT indexname FROM pg_indexes WHERE tablename = 'daily_rank_snapshot' ORDER BY indexname;
