-- mission_reward: daily mission rewards, claimed by the user (BEA-299).
--
-- Flyway is not used in this repository, so this DDL is applied by hand.
-- Production runs ddl-auto=validate: apply this BEFORE deploying the entity,
-- otherwise the application fails to boot.
--
-- Requires app_user to exist (foreign key) and mission_definition to be applied
-- first (docs/sql/mission-definition.sql).
--
-- A row appears when the mission is achieved and stays after it is claimed or
-- expires. Unclaimed rewards die at midnight by product decision, but the row
-- is kept as EXPIRED so "보상을 놓쳤다" can be shown and measured.

BEGIN;

CREATE TABLE mission_reward (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id           UUID NOT NULL,
    user_id             UUID NOT NULL REFERENCES app_user (id),
    mission_code        VARCHAR(60) NOT NULL,
    period_key          VARCHAR(20) NOT NULL,
    reward_point_amount BIGINT NOT NULL,
    status              VARCHAR(20) NOT NULL,
    achieved_at         TIMESTAMPTZ NOT NULL,
    -- 데일리 보상은 그날 자정에 소멸한다. 단발성 보상(알림 허용)은 NULL 이다 — 매일 초기화되는
    -- 미션이 아니라서, 받기를 하루 늦게 눌렀다고 영영 못 받게 할 이유가 없다.
    expires_at          TIMESTAMPTZ,
    claimed_at          TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL,
    updated_at          TIMESTAMPTZ NOT NULL,
    -- 같은 보상을 동시에 받으려는 요청을 막는다. 변경 가능한 엔티티에 버전을 두는 것이 이 저장소 관례다.
    version             BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_mission_reward_amount CHECK (reward_point_amount > 0),
    CONSTRAINT ck_mission_reward_status CHECK (status IN ('CLAIMABLE', 'CLAIMED', 'EXPIRED')),
    CONSTRAINT ck_mission_reward_claimed CHECK (status <> 'CLAIMED' OR claimed_at IS NOT NULL)
);

-- 이중 수령 방어. 같은 미션을 같은 날 두 번 받을 수 없게 하는 것은 이 제약이고,
-- 포인트가 두 번 적립되지 않게 하는 것은 point_ledger 의 (user_id, idempotency_key) 다.
CREATE UNIQUE INDEX uq_mission_reward_user_code_period
    ON mission_reward (user_id, mission_code, period_key);
CREATE UNIQUE INDEX uq_mission_reward_public_id ON mission_reward (public_id);

-- 미션 목록을 열 때마다 (user_id, 오늘·ONCE) 로 조회한다. 가장 잦은 경로다.
CREATE INDEX ix_mission_reward_user_period ON mission_reward (user_id, period_key);

-- 수령 화면과 자정 만료 배치가 쓰는 조회 경로.
CREATE INDEX ix_mission_reward_user_status ON mission_reward (user_id, status, achieved_at DESC);
CREATE INDEX ix_mission_reward_status_expires ON mission_reward (status, expires_at);

COMMIT;

-- Verification after applying:
--   SELECT conname FROM pg_constraint WHERE conrelid = 'mission_reward'::regclass ORDER BY conname;
--   SELECT indexname FROM pg_indexes WHERE tablename = 'mission_reward' ORDER BY indexname;
