-- mission_definition: daily mission catalog (BEA-299).
--
-- Flyway is not used in this repository, so this DDL is applied by hand.
-- Production runs ddl-auto=validate: apply this BEFORE deploying the entity,
-- otherwise the application fails to boot.
--
-- The catalog lives in a table rather than app_config because app_config only
-- ever held scalar values and has no validation for structured payloads: one
-- broken JSON array would take the whole mission list down. A row per mission
-- also means changing one reward is a single UPDATE.
--
-- Run inside a transaction so a partial apply cannot happen.

BEGIN;

CREATE TABLE mission_definition (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                VARCHAR(60) NOT NULL,
    mission_type        VARCHAR(30) NOT NULL,
    period_type         VARCHAR(20) NOT NULL,
    name                VARCHAR(60) NOT NULL,
    description         VARCHAR(200),
    target_value        BIGINT NOT NULL,
    reward_point_amount BIGINT NOT NULL,
    sort_order          INTEGER NOT NULL DEFAULT 0,
    active              BOOLEAN NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMPTZ NOT NULL,
    updated_at          TIMESTAMPTZ NOT NULL,
    CONSTRAINT ck_mission_definition_type
        CHECK (mission_type IN ('ATTENDANCE', 'TAP_COUNT', 'RANK_UP', 'NOTIFICATION_OPT_IN')),
    CONSTRAINT ck_mission_definition_period
        CHECK (period_type IN ('DAILY', 'ONE_TIME')),
    CONSTRAINT ck_mission_definition_reward CHECK (reward_point_amount > 0),
    -- 0 을 허용하면 "current >= target" 이 항상 참이라 전원이 즉시 달성한다. 운영자가 SQL 로
    -- 직접 고치는 테이블이므로 값을 빠뜨린 INSERT 한 줄이 그런 미션을 만들 수 있다.
    CONSTRAINT ck_mission_definition_target CHECK (target_value > 0)
);

CREATE UNIQUE INDEX uq_mission_definition_code ON mission_definition (code);
CREATE INDEX ix_mission_definition_active_sort ON mission_definition (active, sort_order);

-- Seed values confirmed in BEA-300. Amounts are provisional by design: they are
-- meant to be changed with an UPDATE, never with a deploy.
INSERT INTO mission_definition
    (code, mission_type, period_type, name, description, target_value, reward_point_amount, sort_order, active, created_at, updated_at)
VALUES
    ('NOTIFICATION_OPT_IN', 'NOTIFICATION_OPT_IN', 'ONE_TIME', '알림 허용하기', '데일리 미션 알림을 받으면 드려요', 1, 100, 0, TRUE, now(), now()),
    ('ATTENDANCE',          'ATTENDANCE',          'DAILY',    '출석 체크',     '오늘 앱에 들어오면 달성돼요',      1, 100, 10, TRUE, now(), now()),
    ('TAP_100',             'TAP_COUNT',           'DAILY',    '클릭 100번',    NULL,                             100,  10, 20, TRUE, now(), now()),
    ('TAP_500',             'TAP_COUNT',           'DAILY',    '클릭 500번',    NULL,                             500,  15, 30, TRUE, now(), now()),
    ('TAP_1000',            'TAP_COUNT',           'DAILY',    '클릭 1,000번',  NULL,                            1000,  20, 40, TRUE, now(), now()),
    ('TAP_3000',            'TAP_COUNT',           'DAILY',    '클릭 3,000번',  NULL,                            3000,  30, 50, TRUE, now(), now()),
    ('TAP_5000',            'TAP_COUNT',           'DAILY',    '클릭 5,000번',  NULL,                            5000,  50, 60, TRUE, now(), now()),
    ('RANK_UP_5',           'RANK_UP',             'DAILY',    '랭킹 5등 상승',  '어제 순위보다 5등 올라가면 달성돼요',  5, 100, 70, TRUE, now(), now()),
    ('RANK_UP_10',          'RANK_UP',             'DAILY',    '랭킹 10등 상승', '어제 순위보다 10등 올라가면 달성돼요', 10, 200, 80, TRUE, now(), now())
ON CONFLICT (code) DO NOTHING;

COMMIT;

-- Verification after applying:
--   SELECT code, mission_type, period_type, target_value, reward_point_amount, sort_order
--     FROM mission_definition ORDER BY sort_order;
--   SELECT conname FROM pg_constraint WHERE conrelid = 'mission_definition'::regclass ORDER BY conname;
