-- promotion_grant: Toss promotion payout ledger (BEA-271).
--
-- Flyway is not used in this repository, so this DDL is applied by hand.
-- Production runs ddl-auto=validate: apply this BEFORE deploying the entity,
-- otherwise the application fails to boot.
--
-- Requires app_user to exist (foreign key). Run inside a transaction so a
-- missing dependency rolls the whole thing back instead of leaving a half
-- created table.
--
-- Partial indexes live in src/main/resources/db/manual-index-contracts.sql,
-- following the same split used by the notification tables.

CREATE TABLE promotion_grant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL,
    user_id UUID NOT NULL REFERENCES app_user (id),
    promotion_code VARCHAR(80) NOT NULL,
    toss_promotion_code VARCHAR(80),
    amount BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    hold_reason VARCHAR(40),
    needs_review BOOLEAN NOT NULL DEFAULT FALSE,
    toss_promotion_key VARCHAR(255),
    toss_error_code VARCHAR(40),
    failure_reason VARCHAR(255),
    attempt_count INTEGER NOT NULL DEFAULT 0,
    poll_count INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMPTZ NOT NULL,
    trigger_snapshot INTEGER,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    granted_at TIMESTAMPTZ,
    CONSTRAINT ck_promotion_grant_amount CHECK (amount > 0),
    CONSTRAINT ck_promotion_grant_status
        CHECK (status IN ('PENDING', 'PROCESSING', 'SUCCEEDED', 'FAILED'))
);

-- Duplicate payout defence. Toss does not enforce one-per-user; this index is
-- the only thing that does. If it is missing nothing fails until a user is
-- actually paid twice.
CREATE UNIQUE INDEX uq_promotion_grant_user_code ON promotion_grant (user_id, promotion_code);
CREATE UNIQUE INDEX uq_promotion_grant_public_id ON promotion_grant (public_id);

-- Verification after applying:
--   SELECT conname FROM pg_constraint WHERE conrelid = 'promotion_grant'::regclass ORDER BY conname;
--   SELECT indexname FROM pg_indexes WHERE tablename = 'promotion_grant' ORDER BY indexname;
