BEGIN;

CREATE TABLE IF NOT EXISTS weekly_ranking_reward (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id uuid NOT NULL UNIQUE,
    season_id bigint NOT NULL REFERENCES ranking_season(id),
    user_id uuid NOT NULL REFERENCES app_user(id),
    source_final_rank bigint NOT NULL,
    reward_rank integer NOT NULL,
    final_score bigint NOT NULL,
    point_amount bigint NOT NULL,
    status varchar(20) NOT NULL,
    expires_at timestamptz NOT NULL,
    claimed_at timestamptz,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    CONSTRAINT uq_weekly_ranking_reward_season_user UNIQUE (season_id, user_id),
    CONSTRAINT uq_weekly_ranking_reward_season_rank UNIQUE (season_id, reward_rank),
    CONSTRAINT ck_weekly_ranking_reward_positive CHECK (
        source_final_rank > 0 AND reward_rank > 0 AND final_score > 0 AND point_amount > 0
    ),
    CONSTRAINT ck_weekly_ranking_reward_status CHECK (status IN ('OPENED', 'CLAIMED')),
    CONSTRAINT ck_weekly_ranking_reward_claimed CHECK (
        (status = 'OPENED' AND claimed_at IS NULL)
        OR (status = 'CLAIMED' AND claimed_at IS NOT NULL)
    )
);

CREATE INDEX IF NOT EXISTS ix_weekly_ranking_reward_season_rank
    ON weekly_ranking_reward (season_id, reward_rank);
CREATE INDEX IF NOT EXISTS ix_weekly_ranking_reward_user_status_expires
    ON weekly_ranking_reward (user_id, status, expires_at);

INSERT INTO app_config (public_id, config_key, config_value, effective_at, created_at, updated_at)
SELECT gen_random_uuid(), 'ranking.weeklyReward.policy',
       '{"enabled":false,"rewards":{"1":10000,"2":5000,"3":2500}}'::jsonb,
       now(), now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM app_config WHERE config_key = 'ranking.weeklyReward.policy'
);

COMMIT;

SELECT column_name, data_type, is_nullable
FROM information_schema.columns
WHERE table_name = 'weekly_ranking_reward'
ORDER BY ordinal_position;

SELECT conname, pg_get_constraintdef(oid)
FROM pg_constraint
WHERE conrelid = 'weekly_ranking_reward'::regclass;

SELECT indexname, indexdef
FROM pg_indexes
WHERE tablename = 'weekly_ranking_reward';

SELECT config_key, config_value, effective_at
FROM app_config
WHERE config_key = 'ranking.weeklyReward.policy'
ORDER BY effective_at DESC, id DESC
LIMIT 1;
