-- BEA-308: review runtime DB identity/schema, then apply BEFORE deploying this entity mapping.
-- No activation: BEA-296 rollout gate remains closed in code, regardless of enabled=true.
-- Additive migration; no real tap table/data is modified. Run in a short maintenance window.
BEGIN;

ALTER TABLE ranking_entry ADD COLUMN IF NOT EXISTS ranking_boost_score bigint NOT NULL DEFAULT 0;
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'ranking_entry'::regclass
                   AND conname = 'ck_ranking_entry_boost') THEN
        ALTER TABLE ranking_entry ADD CONSTRAINT ck_ranking_entry_boost
            CHECK (ranking_boost_score >= 0 AND score >= ranking_boost_score);
    END IF;
END $$;

-- Audit deliberately has no user/delivery cascade FK: preserve season exclusion evidence
-- even after a user is removed from configuration or a delivery record is retained elsewhere.
CREATE TABLE IF NOT EXISTS ranking_boost_run (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_date date NOT NULL,
    scheduled_at timestamptz NOT NULL,
    event_type varchar(60) NOT NULL,
    status varchar(20) NOT NULL,
    season_id bigint,
    selected_user_id uuid,
    leader_user_id uuid,
    real_score bigint,
    previous_score bigint,
    target_score bigint,
    boost_before bigint,
    boost_after bigint,
    score_increment integer,
    leader_rank_before bigint,
    leader_rank_after bigint,
    policy_snapshot text,
    applied_at timestamptz,
    skip_reason varchar(100),
    notification_delivery_id bigint,
    dispatch_claimed_at timestamptz,
    created_at timestamptz NOT NULL,
    version bigint NOT NULL DEFAULT 0,
    CONSTRAINT uq_ranking_boost_run_date UNIQUE (run_date),
    CONSTRAINT ck_ranking_boost_run_type CHECK (event_type = 'SYSTEM_RANKING_BOOST'),
    CONSTRAINT ck_ranking_boost_run_status CHECK (status IN ('PLANNED', 'APPLIED', 'SKIPPED')),
    CONSTRAINT ck_ranking_boost_run_applied CHECK (status <> 'APPLIED' OR
        (season_id IS NOT NULL AND selected_user_id IS NOT NULL AND leader_user_id IS NOT NULL
         AND real_score IS NOT NULL AND previous_score IS NOT NULL AND target_score IS NOT NULL AND target_score > previous_score
         AND boost_before IS NOT NULL AND boost_after IS NOT NULL AND boost_after > boost_before
         AND score_increment IS NOT NULL AND score_increment > 0
         AND leader_rank_before IS NOT NULL AND leader_rank_before > 0 AND leader_rank_after IS NOT NULL AND leader_rank_after > 0
         AND policy_snapshot IS NOT NULL AND applied_at IS NOT NULL))
);
CREATE INDEX IF NOT EXISTS ix_ranking_boost_run_season_user ON ranking_boost_run (season_id, selected_user_id);

-- Seed only if no operator-managed policy exists. 1000 is an example, not a code constant.
INSERT INTO app_config (public_id, config_key, config_value, effective_at, created_at, updated_at)
SELECT gen_random_uuid(), 'ranking.systemBoost.policy',
       '{"enabled":false,"internalUserIds":[],"minimumLeaderScore":1000,"minIncrement":200,"maxIncrement":500}'::jsonb,
       now(), now(), now()
WHERE NOT EXISTS (SELECT 1 FROM app_config WHERE config_key = 'ranking.systemBoost.policy');

COMMIT;

SELECT column_name, data_type, is_nullable, column_default
FROM information_schema.columns WHERE table_name = 'ranking_entry' AND column_name = 'ranking_boost_score';
SELECT indexname, indexdef FROM pg_indexes WHERE tablename = 'ranking_boost_run';
