-- BEA-309: apply before deploying the weekly ranking reset notification worker.
-- The push continues to use the existing RANK_CHANGE preference and campaign.
BEGIN;

CREATE TABLE IF NOT EXISTS weekly_ranking_reset_notification_batch (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    season_id bigint NOT NULL REFERENCES ranking_season(id),
    preference_cursor bigint NOT NULL DEFAULT 0,
    enqueue_completed boolean NOT NULL DEFAULT false,
    completed boolean NOT NULL DEFAULT false,
    completed_at timestamptz,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    CONSTRAINT uq_weekly_reset_notification_batch_season UNIQUE (season_id),
    CONSTRAINT ck_weekly_reset_notification_batch_cursor CHECK (preference_cursor >= 0),
    CONSTRAINT ck_weekly_reset_notification_batch_completed CHECK (NOT completed OR enqueue_completed)
);

ALTER TABLE notification_delivery
    ADD COLUMN IF NOT EXISTS weekly_reset_batch_id bigint,
    ADD COLUMN IF NOT EXISTS attempt_count integer NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS next_attempt_at timestamptz,
    ADD COLUMN IF NOT EXISTS last_attempt_at timestamptz;

DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'notification_delivery'::regclass
          AND conname = 'fk_notification_delivery_weekly_reset_batch'
    ) THEN
        ALTER TABLE notification_delivery
            ADD CONSTRAINT fk_notification_delivery_weekly_reset_batch
            FOREIGN KEY (weekly_reset_batch_id) REFERENCES weekly_ranking_reset_notification_batch(id);
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'notification_delivery'::regclass
          AND conname = 'ck_notification_delivery_attempt_count'
    ) THEN
        ALTER TABLE notification_delivery
            ADD CONSTRAINT ck_notification_delivery_attempt_count CHECK (attempt_count >= 0);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS ix_weekly_reset_notification_batch_pending
    ON weekly_ranking_reset_notification_batch (id)
    WHERE completed = false;
CREATE INDEX IF NOT EXISTS ix_notification_delivery_weekly_reset_due
    ON notification_delivery (next_attempt_at, id)
    WHERE weekly_reset_batch_id IS NOT NULL AND status IN ('PENDING', 'RETRY_WAITING');

CREATE INDEX IF NOT EXISTS ix_notification_delivery_weekly_reset_last_attempt
    ON notification_delivery (last_attempt_at)
    WHERE weekly_reset_batch_id IS NOT NULL;

INSERT INTO app_config (public_id, config_key, config_value, effective_at, created_at, updated_at)
SELECT gen_random_uuid(), 'notification.rankChange.minimumDifference', '1'::jsonb, now(), now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM app_config WHERE config_key = 'notification.rankChange.minimumDifference'
);

COMMIT;

SELECT column_name, data_type, is_nullable, column_default
FROM information_schema.columns
WHERE table_name = 'notification_delivery'
  AND column_name IN ('weekly_reset_batch_id', 'attempt_count', 'next_attempt_at', 'last_attempt_at')
ORDER BY column_name;

SELECT config_key, config_value, effective_at
FROM app_config
WHERE config_key = 'notification.rankChange.minimumDifference'
ORDER BY effective_at DESC, id DESC
LIMIT 1;
