CREATE TABLE auth_session_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    user_public_id UUID,
    device_public_id UUID,
    session_id_hash VARCHAR(128),
    token_family_id_hash VARCHAR(128),
    event_type VARCHAR(40) NOT NULL,
    result VARCHAR(20) NOT NULL,
    failure_code VARCHAR(80),
    trace_id VARCHAR(80),
    ip_address_masked VARCHAR(80),
    user_agent VARCHAR(512),
    metadata JSONB,
    occurred_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT ck_auth_session_log_result CHECK (result IN ('SUCCESS', 'FAILURE', 'DENIED'))
);

CREATE INDEX ix_auth_session_log_user_time ON auth_session_log (user_public_id, occurred_at);
CREATE INDEX ix_auth_session_log_session_time ON auth_session_log (session_id_hash, occurred_at);
CREATE INDEX ix_auth_session_log_event_time ON auth_session_log (event_type, occurred_at);
CREATE INDEX ix_auth_session_log_trace ON auth_session_log (trace_id);
