CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    nickname VARCHAR(50),
    nickname_normalized VARCHAR(50),
    last_login_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT ck_app_user_status CHECK (status IN ('ACTIVE', 'SUSPENDED', 'WITHDRAWN'))
);

CREATE INDEX ix_app_user_status ON app_user (status);
CREATE UNIQUE INDEX ux_app_user_active_nickname_normalized
    ON app_user (nickname_normalized)
    WHERE nickname_normalized IS NOT NULL AND status = 'ACTIVE';

CREATE TABLE auth_identity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    provider VARCHAR(30) NOT NULL,
    provider_user_id VARCHAR(255) NOT NULL,
    linked_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_auth_identity_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE RESTRICT,
    CONSTRAINT ck_auth_identity_provider CHECK (provider IN ('TOSS')),
    CONSTRAINT ux_auth_identity_provider_user UNIQUE (provider, provider_user_id),
    CONSTRAINT ux_auth_identity_user_provider UNIQUE (user_id, provider)
);

CREATE INDEX ix_auth_identity_user_id ON auth_identity (user_id);

CREATE TABLE legal_document (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    document_type VARCHAR(30) NOT NULL,
    version VARCHAR(30) NOT NULL,
    title VARCHAR(100) NOT NULL,
    content TEXT NOT NULL,
    effective_at TIMESTAMPTZ NOT NULL,
    active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT ck_legal_document_type CHECK (document_type IN ('TERMS', 'PRIVACY', 'BUSINESS_INFO')),
    CONSTRAINT ux_legal_document_type_version UNIQUE (document_type, version)
);

CREATE INDEX ix_legal_document_current ON legal_document (document_type, active, effective_at);

CREATE TABLE user_consent (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    document_type VARCHAR(30) NOT NULL,
    version VARCHAR(30) NOT NULL,
    consented_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_user_consent_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE RESTRICT,
    CONSTRAINT ux_user_consent_doc UNIQUE (user_id, document_type, version)
);

CREATE TABLE app_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    config_key VARCHAR(80) NOT NULL,
    config_value JSONB NOT NULL,
    effective_at TIMESTAMPTZ NOT NULL,
    created_by VARCHAR(80),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT ux_app_config_key_effective UNIQUE (config_key, effective_at)
);

CREATE INDEX ix_app_config_active ON app_config (config_key, effective_at);

CREATE TABLE keycap (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    code VARCHAR(60) NOT NULL UNIQUE,
    name VARCHAR(80) NOT NULL UNIQUE,
    grade VARCHAR(20) NOT NULL,
    required_shard_count INTEGER NOT NULL,
    image_url TEXT,
    limited BOOLEAN NOT NULL DEFAULT false,
    active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT ck_keycap_grade CHECK (grade IN ('COMMON', 'RARE', 'EPIC', 'LEGENDARY', 'LIMITED')),
    CONSTRAINT ck_keycap_required_shard_count CHECK (required_shard_count > 0)
);

CREATE INDEX ix_keycap_active_grade ON keycap (active, grade);

CREATE TABLE keycap_drop_table (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    priority INTEGER NOT NULL DEFAULT 0,
    purpose VARCHAR(20) NOT NULL DEFAULT 'STANDARD',
    active_from TIMESTAMPTZ NOT NULL,
    active_until TIMESTAMPTZ,
    active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT ck_keycap_drop_table_purpose CHECK (purpose IN ('STANDARD')),
    CONSTRAINT ck_keycap_drop_table_period CHECK (active_until IS NULL OR active_until > active_from)
);

CREATE INDEX ix_keycap_drop_table_active ON keycap_drop_table (active, active_from, active_until, priority);

CREATE TABLE keycap_drop_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    drop_table_id BIGINT NOT NULL,
    keycap_id BIGINT NOT NULL,
    grant_mode VARCHAR(20) NOT NULL DEFAULT 'SHARD',
    shard_count INTEGER,
    weight INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_keycap_drop_item_drop_table FOREIGN KEY (drop_table_id) REFERENCES keycap_drop_table (id) ON DELETE RESTRICT,
    CONSTRAINT fk_keycap_drop_item_keycap FOREIGN KEY (keycap_id) REFERENCES keycap (id) ON DELETE RESTRICT,
    CONSTRAINT ck_keycap_drop_item_grant_mode CHECK (grant_mode IN ('SHARD', 'COMPLETE_KEYCAP')),
    CONSTRAINT ck_keycap_drop_item_shard_count CHECK (
        (grant_mode = 'SHARD' AND shard_count IS NOT NULL AND shard_count > 0)
        OR (grant_mode = 'COMPLETE_KEYCAP' AND shard_count IS NULL)
    ),
    CONSTRAINT ck_keycap_drop_item_weight CHECK (weight > 0)
);

CREATE INDEX ix_keycap_drop_item_table ON keycap_drop_item (drop_table_id);

CREATE TABLE user_keycap (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    keycap_id BIGINT NOT NULL,
    shard_count INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'IN_PROGRESS',
    equipped BOOLEAN NOT NULL DEFAULT false,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_user_keycap_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE RESTRICT,
    CONSTRAINT fk_user_keycap_keycap FOREIGN KEY (keycap_id) REFERENCES keycap (id) ON DELETE RESTRICT,
    CONSTRAINT ck_user_keycap_shard_count CHECK (shard_count >= 0),
    CONSTRAINT ck_user_keycap_status CHECK (status IN ('IN_PROGRESS', 'COMPLETED')),
    CONSTRAINT ux_user_keycap_user_keycap UNIQUE (user_id, keycap_id)
);

CREATE UNIQUE INDEX ux_user_keycap_equipped ON user_keycap (user_id) WHERE equipped = true;

CREATE TABLE keycap_box_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    user_id BIGINT NOT NULL UNIQUE,
    balance INTEGER NOT NULL DEFAULT 0,
    next_free_open_at TIMESTAMPTZ,
    ad_open_date DATE,
    ad_open_count INTEGER NOT NULL DEFAULT 0,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_keycap_box_account_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE RESTRICT,
    CONSTRAINT ck_keycap_box_account_balance CHECK (balance >= 0),
    CONSTRAINT ck_keycap_box_account_ad_open_count CHECK (ad_open_count >= 0)
);

CREATE TABLE keycap_box_ledger (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    change_amount INTEGER NOT NULL,
    reason VARCHAR(40) NOT NULL,
    reference_type VARCHAR(50) NOT NULL,
    reference_id VARCHAR(100) NOT NULL,
    balance_after INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_keycap_box_ledger_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE RESTRICT,
    CONSTRAINT ck_keycap_box_ledger_change_amount CHECK (change_amount <> 0),
    CONSTRAINT ck_keycap_box_ledger_balance_after CHECK (balance_after >= 0),
    CONSTRAINT ux_keycap_box_ledger_ref UNIQUE (reference_type, reference_id, reason)
);

CREATE INDEX ix_keycap_box_ledger_user_created ON keycap_box_ledger (user_id, created_at);

CREATE TABLE keycap_box_open (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    open_method VARCHAR(20) NOT NULL,
    ad_view_id UUID,
    open_count INTEGER NOT NULL DEFAULT 1,
    status VARCHAR(20) NOT NULL DEFAULT 'COMPLETED',
    idempotency_key VARCHAR(100) NOT NULL,
    opened_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_keycap_box_open_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE RESTRICT,
    CONSTRAINT ck_keycap_box_open_method CHECK (open_method IN ('FREE', 'ADVERTISEMENT')),
    CONSTRAINT ck_keycap_box_open_count CHECK (open_count = 1),
    CONSTRAINT ck_keycap_box_open_status CHECK (status IN ('COMPLETED', 'FAILED')),
    CONSTRAINT ux_keycap_box_open_idem UNIQUE (user_id, idempotency_key)
);

CREATE UNIQUE INDEX ux_keycap_box_open_ad_view
    ON keycap_box_open (ad_view_id)
    WHERE open_method = 'ADVERTISEMENT';

CREATE TABLE keycap_box_open_result (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    open_id BIGINT NOT NULL UNIQUE,
    keycap_id BIGINT NOT NULL,
    shard_count INTEGER NOT NULL,
    completed BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_keycap_box_open_result_open FOREIGN KEY (open_id) REFERENCES keycap_box_open (id) ON DELETE RESTRICT,
    CONSTRAINT fk_keycap_box_open_result_keycap FOREIGN KEY (keycap_id) REFERENCES keycap (id) ON DELETE RESTRICT,
    CONSTRAINT ck_keycap_box_open_result_shard_count CHECK (shard_count > 0)
);

CREATE TABLE region (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    sido VARCHAR(50) NOT NULL,
    sigungu VARCHAR(80) NOT NULL,
    code VARCHAR(30) NOT NULL UNIQUE,
    active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX ix_region_active_sido ON region (active, sido, sigungu);

CREATE TABLE user_region (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    user_id BIGINT NOT NULL UNIQUE,
    region_id BIGINT NOT NULL,
    effective_from TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_user_region_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE RESTRICT,
    CONSTRAINT fk_user_region_region FOREIGN KEY (region_id) REFERENCES region (id) ON DELETE RESTRICT
);

CREATE TABLE user_region_change (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    from_region_id BIGINT,
    to_region_id BIGINT NOT NULL,
    change_month VARCHAR(7) NOT NULL,
    effective_at TIMESTAMPTZ NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'SCHEDULED',
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_user_region_change_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE RESTRICT,
    CONSTRAINT fk_user_region_change_from_region FOREIGN KEY (from_region_id) REFERENCES region (id) ON DELETE RESTRICT,
    CONSTRAINT fk_user_region_change_to_region FOREIGN KEY (to_region_id) REFERENCES region (id) ON DELETE RESTRICT,
    CONSTRAINT ck_user_region_change_status CHECK (status IN ('SCHEDULED', 'APPLIED', 'CANCELED')),
    CONSTRAINT ux_user_region_change_month UNIQUE (user_id, change_month)
);

CREATE UNIQUE INDEX ux_user_region_change_scheduled
    ON user_region_change (user_id)
    WHERE status = 'SCHEDULED';

CREATE TABLE ranking_season (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    round_number INTEGER NOT NULL UNIQUE,
    starts_at TIMESTAMPTZ NOT NULL,
    ends_at TIMESTAMPTZ NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT ck_ranking_season_status CHECK (status IN ('ACTIVE', 'SETTLING', 'SETTLED')),
    CONSTRAINT ck_ranking_season_period CHECK (ends_at > starts_at),
    CONSTRAINT ux_ranking_season_period UNIQUE (starts_at, ends_at)
);

CREATE TABLE ranking_participation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    season_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    joined_at TIMESTAMPTZ NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'JOINED',
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_ranking_participation_season FOREIGN KEY (season_id) REFERENCES ranking_season (id) ON DELETE RESTRICT,
    CONSTRAINT fk_ranking_participation_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE RESTRICT,
    CONSTRAINT ck_ranking_participation_status CHECK (status IN ('JOINED', 'CANCELED')),
    CONSTRAINT ux_ranking_participation_user UNIQUE (season_id, user_id)
);

CREATE TABLE ranking_score (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    participation_id BIGINT NOT NULL UNIQUE,
    score BIGINT NOT NULL DEFAULT 0,
    reached_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_ranking_score_participation FOREIGN KEY (participation_id) REFERENCES ranking_participation (id) ON DELETE RESTRICT,
    CONSTRAINT ck_ranking_score_score CHECK (score >= 0)
);

CREATE INDEX ix_ranking_score_score ON ranking_score (score DESC, reached_at ASC);

CREATE TABLE ranking_score_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    season_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    source_type VARCHAR(40) NOT NULL,
    source_event_id VARCHAR(100) NOT NULL,
    score_delta BIGINT NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_ranking_score_event_season FOREIGN KEY (season_id) REFERENCES ranking_season (id) ON DELETE RESTRICT,
    CONSTRAINT fk_ranking_score_event_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE RESTRICT,
    CONSTRAINT ck_ranking_score_event_score_delta CHECK (score_delta > 0),
    CONSTRAINT ux_ranking_score_event_source UNIQUE (source_type, source_event_id)
);

CREATE TABLE ranking_snapshot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    season_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    final_rank INTEGER NOT NULL,
    final_score BIGINT NOT NULL,
    reached_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_ranking_snapshot_season FOREIGN KEY (season_id) REFERENCES ranking_season (id) ON DELETE RESTRICT,
    CONSTRAINT fk_ranking_snapshot_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE RESTRICT,
    CONSTRAINT ck_ranking_snapshot_final_rank CHECK (final_rank > 0),
    CONSTRAINT ck_ranking_snapshot_final_score CHECK (final_score >= 0),
    CONSTRAINT ux_ranking_snapshot_user UNIQUE (season_id, user_id)
);

CREATE INDEX ix_ranking_snapshot_rank ON ranking_snapshot (season_id, final_rank);

CREATE TABLE ranking_reward (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    season_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    reward_type VARCHAR(40) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'GRANTED',
    keycap_id BIGINT,
    granted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_ranking_reward_season FOREIGN KEY (season_id) REFERENCES ranking_season (id) ON DELETE RESTRICT,
    CONSTRAINT fk_ranking_reward_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE RESTRICT,
    CONSTRAINT fk_ranking_reward_keycap FOREIGN KEY (keycap_id) REFERENCES keycap (id) ON DELETE RESTRICT,
    CONSTRAINT ck_ranking_reward_status CHECK (status IN ('GRANTED', 'FAILED')),
    CONSTRAINT ux_ranking_reward_once UNIQUE (season_id, user_id, reward_type)
);

CREATE TABLE push_device (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    push_token_ciphertext TEXT NOT NULL,
    push_token_hash VARCHAR(255) NOT NULL UNIQUE,
    platform VARCHAR(20) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT true,
    last_seen_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_push_device_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE RESTRICT,
    CONSTRAINT ck_push_device_platform CHECK (platform IN ('IOS', 'ANDROID'))
);

CREATE INDEX ix_push_device_user_active ON push_device (user_id, active);

CREATE TABLE notification_preference (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    type VARCHAR(40) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT true,
    reminder_time TIME,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_notification_preference_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE RESTRICT,
    CONSTRAINT ux_notification_preference_user_type UNIQUE (user_id, type)
);

CREATE TABLE notification_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    push_device_id BIGINT NOT NULL,
    type VARCHAR(40) NOT NULL,
    title VARCHAR(100) NOT NULL,
    body VARCHAR(500),
    dedupe_key VARCHAR(120) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'READY',
    sent_at TIMESTAMPTZ,
    opened_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_notification_log_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE RESTRICT,
    CONSTRAINT fk_notification_log_push_device FOREIGN KEY (push_device_id) REFERENCES push_device (id) ON DELETE RESTRICT,
    CONSTRAINT ck_notification_log_status CHECK (status IN ('READY', 'SENT', 'FAILED', 'OPENED')),
    CONSTRAINT ux_notification_log_dedupe_device UNIQUE (dedupe_key, push_device_id)
);

CREATE INDEX ix_notification_log_user_created ON notification_log (user_id, created_at);

CREATE TABLE user_record_daily (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    record_date DATE NOT NULL,
    tap_count BIGINT NOT NULL DEFAULT 0,
    point_amount BIGINT NOT NULL DEFAULT 0,
    box_count INTEGER NOT NULL DEFAULT 0,
    completed_keycap_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_user_record_daily_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE RESTRICT,
    CONSTRAINT ck_user_record_daily_tap_count CHECK (tap_count >= 0),
    CONSTRAINT ck_user_record_daily_point_amount CHECK (point_amount >= 0),
    CONSTRAINT ck_user_record_daily_box_count CHECK (box_count >= 0),
    CONSTRAINT ck_user_record_daily_completed_keycap_count CHECK (completed_keycap_count >= 0),
    CONSTRAINT ux_user_record_daily_user_date UNIQUE (user_id, record_date)
);

CREATE TABLE user_record_summary (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    user_id BIGINT NOT NULL UNIQUE,
    total_tap_count BIGINT NOT NULL DEFAULT 0,
    total_point_amount BIGINT NOT NULL DEFAULT 0,
    total_box_count INTEGER NOT NULL DEFAULT 0,
    completed_keycap_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_user_record_summary_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE RESTRICT,
    CONSTRAINT ck_user_record_summary_total_tap_count CHECK (total_tap_count >= 0),
    CONSTRAINT ck_user_record_summary_total_point_amount CHECK (total_point_amount >= 0),
    CONSTRAINT ck_user_record_summary_total_box_count CHECK (total_box_count >= 0),
    CONSTRAINT ck_user_record_summary_completed_keycap_count CHECK (completed_keycap_count >= 0)
);

CREATE TABLE user_record_reward (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    reference_type VARCHAR(50) NOT NULL,
    reference_id VARCHAR(100) NOT NULL,
    reward_type VARCHAR(50) NOT NULL,
    amount BIGINT,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_user_record_reward_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE RESTRICT,
    CONSTRAINT ux_user_record_reward_ref UNIQUE (user_id, reference_type, reference_id, reward_type)
);

CREATE TABLE event_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id UUID NOT NULL UNIQUE,
    aggregate_type VARCHAR(60) NOT NULL,
    aggregate_id VARCHAR(100) NOT NULL,
    event_type VARCHAR(80) NOT NULL,
    payload JSONB NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'READY',
    retry_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT ck_event_outbox_status CHECK (status IN ('READY', 'PUBLISHED', 'FAILED')),
    CONSTRAINT ck_event_outbox_retry_count CHECK (retry_count >= 0)
);

CREATE INDEX ix_event_outbox_status_created ON event_outbox (status, created_at);

CREATE TABLE event_inbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id UUID NOT NULL UNIQUE,
    source VARCHAR(40) NOT NULL,
    event_type VARCHAR(80) NOT NULL,
    payload JSONB NOT NULL,
    processed_at TIMESTAMPTZ,
    failure_code VARCHAR(80),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX ix_event_inbox_processed ON event_inbox (processed_at, created_at);
