CREATE TABLE app_user (
    id UUID PRIMARY KEY,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    nickname VARCHAR(50),
    nickname_normalized VARCHAR(50),
    profile_image_url TEXT,
    onboarding_reward_claimed BOOLEAN NOT NULL DEFAULT false,
    onboarding_completed_at TIMESTAMPTZ,
    last_login_at TIMESTAMPTZ,
    withdrawn_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_app_user_status CHECK (status IN ('ACTIVE', 'SUSPENDED', 'WITHDRAWN')),
    CONSTRAINT ck_app_user_withdrawn_at CHECK ((status = 'WITHDRAWN' AND withdrawn_at IS NOT NULL) OR status <> 'WITHDRAWN')
);

CREATE INDEX ix_app_user_status ON app_user (status);
CREATE UNIQUE INDEX ux_app_user_active_nickname_normalized
    ON app_user (nickname_normalized)
    WHERE nickname_normalized IS NOT NULL AND status = 'ACTIVE';

CREATE TABLE auth_identity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    user_id UUID NOT NULL,
    provider VARCHAR(30) NOT NULL,
    provider_user_id VARCHAR(255) NOT NULL,
    linked_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_auth_identity_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE RESTRICT,
    CONSTRAINT ck_auth_identity_provider CHECK (provider IN ('TOSS')),
    CONSTRAINT ux_auth_identity_provider_user UNIQUE (provider, provider_user_id),
    CONSTRAINT ux_auth_identity_user_provider UNIQUE (user_id, provider)
);

CREATE INDEX ix_auth_identity_user_id ON auth_identity (user_id);

CREATE TABLE app_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    config_key VARCHAR(80) NOT NULL,
    config_value JSONB NOT NULL,
    effective_at TIMESTAMPTZ NOT NULL,
    created_by VARCHAR(80),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ux_app_config_key_effective UNIQUE (config_key, effective_at)
);

CREATE INDEX ix_app_config_active ON app_config (config_key, effective_at);

CREATE TABLE keycap (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    code VARCHAR(60) NOT NULL UNIQUE,
    name VARCHAR(80) NOT NULL,
    grade VARCHAR(20) NOT NULL,
    required_shard_count INTEGER NOT NULL,
    season INTEGER NOT NULL DEFAULT 1,
    image_url TEXT,
    sound_url TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_keycap_grade CHECK (grade IN ('COMMON', 'RARE', 'EPIC', 'LEGENDARY')),
    CONSTRAINT ck_keycap_required_shard_count CHECK (required_shard_count > 0)
);

CREATE INDEX ix_keycap_active_sort ON keycap (active, sort_order);

CREATE TABLE user_keycap (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    user_id UUID NOT NULL,
    keycap_id BIGINT NOT NULL,
    shard_count INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'IN_PROGRESS',
    equipped BOOLEAN NOT NULL DEFAULT false,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_user_keycap_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE RESTRICT,
    CONSTRAINT fk_user_keycap_keycap FOREIGN KEY (keycap_id) REFERENCES keycap (id) ON DELETE RESTRICT,
    CONSTRAINT ck_user_keycap_shard_count CHECK (shard_count >= 0),
    CONSTRAINT ck_user_keycap_status CHECK (status IN ('IN_PROGRESS', 'COMPLETED')),
    CONSTRAINT ux_user_keycap_user_keycap UNIQUE (user_id, keycap_id)
);

CREATE UNIQUE INDEX ux_user_keycap_equipped ON user_keycap (user_id) WHERE equipped = true;
CREATE INDEX ix_user_keycap_user_status ON user_keycap (user_id, status);

CREATE TABLE keycap_box_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    user_id UUID NOT NULL UNIQUE,
    box_balance INTEGER NOT NULL DEFAULT 0,
    free_open_ticket_count INTEGER NOT NULL DEFAULT 0,
    next_free_ticket_at TIMESTAMPTZ,
    ad_open_date DATE,
    ad_open_count INTEGER NOT NULL DEFAULT 0,
    box_progress_tap_count INTEGER NOT NULL DEFAULT 0,
    next_box_required_tap_count INTEGER,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_keycap_box_account_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE RESTRICT,
    CONSTRAINT ck_keycap_box_account_box_balance CHECK (box_balance >= 0),
    CONSTRAINT ck_keycap_box_account_free_tickets CHECK (free_open_ticket_count >= 0),
    CONSTRAINT ck_keycap_box_account_ad_open_count CHECK (ad_open_count >= 0),
    CONSTRAINT ck_keycap_box_account_box_progress CHECK (box_progress_tap_count >= 0)
);

CREATE TABLE keycap_box_open (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    user_id UUID NOT NULL,
    open_method VARCHAR(20) NOT NULL,
    idempotency_key VARCHAR(100) NOT NULL,
    ad_reward_id VARCHAR(255),
    keycap_id BIGINT NOT NULL,
    shard_count INTEGER NOT NULL,
    boost_applied BOOLEAN NOT NULL DEFAULT false,
    completed BOOLEAN NOT NULL DEFAULT false,
    opened_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_keycap_box_open_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE RESTRICT,
    CONSTRAINT fk_keycap_box_open_keycap FOREIGN KEY (keycap_id) REFERENCES keycap (id) ON DELETE RESTRICT,
    CONSTRAINT ck_keycap_box_open_method CHECK (open_method IN ('FREE', 'ADVERTISEMENT')),
    CONSTRAINT ck_keycap_box_open_shard_count CHECK (shard_count > 0),
    CONSTRAINT ux_keycap_box_open_idem UNIQUE (user_id, idempotency_key)
);

CREATE UNIQUE INDEX ux_keycap_box_open_ad_reward
    ON keycap_box_open (ad_reward_id)
    WHERE ad_reward_id IS NOT NULL;
CREATE INDEX ix_keycap_box_open_user_time ON keycap_box_open (user_id, opened_at DESC);

CREATE TABLE tap_batch (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    user_id UUID NOT NULL,
    tap_session_id UUID NOT NULL,
    sequence BIGINT NOT NULL,
    submitted_count INTEGER NOT NULL,
    accepted_count INTEGER NOT NULL DEFAULT 0,
    rejected_count INTEGER NOT NULL DEFAULT 0,
    started_at TIMESTAMPTZ NOT NULL,
    ended_at TIMESTAMPTZ NOT NULL,
    elapsed_ms INTEGER NOT NULL,
    interval_stats JSONB,
    risk_level VARCHAR(20) NOT NULL DEFAULT 'NORMAL',
    status VARCHAR(20) NOT NULL DEFAULT 'RECEIVED',
    request_hash VARCHAR(255) NOT NULL,
    processed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_tap_batch_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE RESTRICT,
    CONSTRAINT ux_tap_batch_session_sequence UNIQUE (user_id, tap_session_id, sequence),
    CONSTRAINT ck_tap_batch_risk_level CHECK (risk_level IN ('NORMAL', 'SUSPICIOUS', 'BLOCKED')),
    CONSTRAINT ck_tap_batch_status CHECK (status IN ('RECEIVED', 'ACCEPTED', 'PARTIAL', 'REJECTED')),
    CONSTRAINT ck_tap_batch_counts CHECK (submitted_count >= 0 AND accepted_count >= 0 AND rejected_count >= 0 AND accepted_count + rejected_count <= submitted_count),
    CONSTRAINT ck_tap_batch_period CHECK (ended_at >= started_at)
);

CREATE INDEX ix_tap_batch_user_created ON tap_batch (user_id, created_at DESC);
CREATE INDEX ix_tap_batch_status_created ON tap_batch (status, created_at);

CREATE TABLE user_tap_daily (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    user_id UUID NOT NULL,
    tap_date DATE NOT NULL,
    valid_tap_count INTEGER NOT NULL DEFAULT 0,
    point_earned_amount INTEGER NOT NULL DEFAULT 0,
    box_dropped_count INTEGER NOT NULL DEFAULT 0,
    ad_box_open_count INTEGER NOT NULL DEFAULT 0,
    booster_used_count INTEGER NOT NULL DEFAULT 0,
    point_progress_remainder INTEGER NOT NULL DEFAULT 0,
    daily_point_limit_reached BOOLEAN NOT NULL DEFAULT false,
    last_batch_sequence BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_user_tap_daily_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE RESTRICT,
    CONSTRAINT ux_user_tap_daily UNIQUE (user_id, tap_date),
    CONSTRAINT ck_user_tap_daily_counts CHECK (
        valid_tap_count >= 0
        AND point_earned_amount >= 0
        AND box_dropped_count >= 0
        AND ad_box_open_count >= 0
        AND booster_used_count >= 0
        AND point_progress_remainder >= 0
    )
);

CREATE TABLE point_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    user_id UUID NOT NULL UNIQUE,
    balance BIGINT NOT NULL DEFAULT 0,
    lifetime_earned BIGINT NOT NULL DEFAULT 0,
    lifetime_spent BIGINT NOT NULL DEFAULT 0,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_point_account_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE RESTRICT,
    CONSTRAINT ck_point_account_amounts CHECK (balance >= 0 AND lifetime_earned >= 0 AND lifetime_spent >= 0)
);

CREATE TABLE point_ledger (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    point_account_id BIGINT NOT NULL,
    user_id UUID NOT NULL,
    entry_type VARCHAR(20) NOT NULL,
    amount BIGINT NOT NULL,
    reason VARCHAR(50) NOT NULL,
    reference_type VARCHAR(40) NOT NULL,
    reference_id UUID NOT NULL,
    idempotency_key UUID,
    balance_after BIGINT NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_point_ledger_account FOREIGN KEY (point_account_id) REFERENCES point_account (id) ON DELETE RESTRICT,
    CONSTRAINT fk_point_ledger_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE RESTRICT,
    CONSTRAINT ck_point_ledger_entry_type CHECK (entry_type IN ('CREDIT', 'DEBIT', 'REVERSAL')),
    CONSTRAINT ck_point_ledger_amount CHECK (amount > 0),
    CONSTRAINT ck_point_ledger_balance_after CHECK (balance_after >= 0),
    CONSTRAINT ux_point_ledger_reference UNIQUE (user_id, reference_type, reference_id, reason)
);

CREATE UNIQUE INDEX ux_point_ledger_idempotency_key
    ON point_ledger (idempotency_key)
    WHERE idempotency_key IS NOT NULL;

CREATE TABLE cashout_request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    user_id UUID NOT NULL,
    point_amount BIGINT NOT NULL,
    toss_point_amount BIGINT NOT NULL,
    exchange_rate NUMERIC(5,2) NOT NULL DEFAULT 0.70,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    idempotency_key UUID NOT NULL,
    provider_transfer_id VARCHAR(255),
    provider_code VARCHAR(80),
    failure_code VARCHAR(80),
    requested_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_cashout_request_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE RESTRICT,
    CONSTRAINT ux_cashout_request_idem UNIQUE (user_id, idempotency_key),
    CONSTRAINT ck_cashout_request_status CHECK (status IN ('PENDING', 'PROCESSING', 'SUCCEEDED', 'FAILED', 'CANCELED')),
    CONSTRAINT ck_cashout_request_amounts CHECK (point_amount > 0 AND toss_point_amount > 0)
);

CREATE UNIQUE INDEX ux_cashout_request_provider_transfer
    ON cashout_request (provider_transfer_id)
    WHERE provider_transfer_id IS NOT NULL;
CREATE INDEX ix_cashout_request_user_time ON cashout_request (user_id, requested_at DESC);
CREATE INDEX ix_cashout_request_status ON cashout_request (status, requested_at);

CREATE TABLE booster_grant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    user_id UUID NOT NULL,
    grant_date DATE NOT NULL,
    daily_sequence INTEGER NOT NULL,
    multiplier NUMERIC(3,1) NOT NULL DEFAULT 2.0,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    ad_reward_id VARCHAR(255),
    starts_at TIMESTAMPTZ NOT NULL,
    ends_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_booster_grant_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE RESTRICT,
    CONSTRAINT ux_booster_grant_daily_sequence UNIQUE (user_id, grant_date, daily_sequence),
    CONSTRAINT ck_booster_grant_status CHECK (status IN ('ACTIVE', 'EXPIRED', 'CANCELED')),
    CONSTRAINT ck_booster_grant_period CHECK (ends_at > starts_at),
    CONSTRAINT ck_booster_grant_multiplier CHECK (multiplier > 1.0)
);

CREATE UNIQUE INDEX ux_booster_grant_ad_reward
    ON booster_grant (ad_reward_id)
    WHERE ad_reward_id IS NOT NULL;
