name: Ggukmoney Backend CI

on:
  pull_request:
    branches:
      - develop
      - main
  push:
    branches:
      - develop

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '26'
          distribution: 'temurin'
          cache: gradle

      - name: Grant Gradle permission
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew clean build
